In [122]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [148]:
df = pd.read_csv('survey lung cancer.csv')
df.head()
df['LUNG_CANCER'].value_counts()

YES    270
NO      39
Name: LUNG_CANCER, dtype: int64

In [124]:
df.drop_duplicates(inplace=True)    # inplace is for overwriting
df.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [125]:
df.GENDER[df.GENDER == 'M'] = 1
df.GENDER[df.GENDER == 'F'] = 0

df.LUNG_CANCER[df.LUNG_CANCER == 'YES'] = 1
df.LUNG_CANCER[df.LUNG_CANCER == 'NO'] = 0

df.drop_duplicates(inplace=True)
df.head()

C:\Users\varun\AppData\Local\Temp/ipykernel_6336/1268106344.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.GENDER[df.GENDER == 'M'] = 1
C:\Users\varun\AppData\Local\Temp/ipykernel_6336/1268106344.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.GENDER[df.GENDER == 'F'] = 0
C:\Users\varun\AppData\Local\Temp/ipykernel_6336/1268106344.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.LUNG_CANCER[df.LUNG_CANCER == 'YES']

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      1   69        1               2        2              1   
1      1   74        2               1        1              1   
2      0   59        1               1        1              2   
3      1   63        2               2        2              1   
4      0   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2           1  
1                    2                      2           2           1  
2                    2                      1           2           0  
3                    1                      2           2           0  
4                    2                      1           1           0

In [126]:
X_total = df.drop(['LUNG_CANCER'], axis=1)

# Changing 2,1 --> 1,0
for i in X_total.columns[2:]:
    temp=[]
    for j in X_total[i]:
        temp.append(j-1)
    X_total[i]=temp

input = X_total.shape[0]
features = X_total.shape[1]

X_total.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      1   69        0               1        1              0   
1      1   74        1               0        0              0   
2      0   59        0               0        0              1   
3      1   63        1               1        1              0   
4      0   63        0               1        0              0   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                0         1         0         1                  1         1   
1                1         1         1         0                  0         0   
2                0         1         0         1                  0         1   
3                0         0         0         0                  1         0   
4                0         0         0         1                  0         1   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  
0                    1                      1           1  
1                    1                      1           1  
2                    1                      0           1  
3                    0                      1           1  
4                    1                      0           0

In [127]:
y_total = df['LUNG_CANCER']
y_total.value_counts()

1    238
0     38
Name: LUNG_CANCER, dtype: int64

In [128]:
X_total['AGE'] = (X_total['AGE'] - X_total['AGE'].mean())/X_total['AGE'].std()
X_total.head()

GENDER       AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      1  0.726855        0               1        1              0   
1      1  1.323560        1               0        0              0   
2      0 -0.466554        0               0        0              1   
3      1  0.010810        1               1        1              0   
4      0  0.010810        0               1        0              0   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                0         1         0         1                  1         1   
1                1         1         1         0                  0         0   
2                0         1         0         1                  0         1   
3                0         0         0         0                  1         0   
4                0         0         0         1                  0         1   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  
0                    1                      1           1  
1                    1                      1           1  
2                    1                      0           1  
3                    0                      1           1  
4                    1                      0           0

In [129]:
X_total = np.array(X_total)
y_total = np.array(y_total)

print('X: ' ,(X_total.shape))
print('Y: ' ,(y_total.shape))

X:  (276, 15)
Y:  (276,)


In [130]:
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X_total, y_total, test_size=0.2, random_state=10)
y_train = np.array(y_train)
y_test = np.array(y_test)

In [142]:
print('X_train: ' ,(X_train.shape))
print('Y_train: ' ,(y_train.shape))
print('X_test:  ' ,(X_test.shape))
print('Y_test:  ' ,(y_test.shape))

count = 0
for i in y_train :
    if i == 0:
        count += 1

print(count)
y_train = y_train.reshape(y_train.shape[0],1)
y_test = y_test.reshape(y_test.shape[0],1)

X_train:  (220, 15)
Y_train:  (220, 1)
X_test:   (56, 15)
Y_test:   (56, 1)
32


In [132]:
def sigmoid(Z) :
    Z = np.asarray(Z, dtype = np.float64)
    return(1/(1+np.exp(-Z)))

In [133]:
def initialize_parameters(n_x, n_h, n_y):
    """
    Argument:
    n_x -- size of the input layer
    n_h -- size of the hidden layer
    n_y -- size of the output layer
    
    Returns:
    params -- python dictionary containing your parameters:
                    W1 -- weight matrix of shape (n_x,n_h)
                    b1 -- bias vector of shape (1,n_h)
                    W2 -- weight matrix of shape (n_h,n_y)
                    b2 -- bias vector of shape (1,n_y)
    """
    
    W1 = np.random.randn(n_x,n_h) * 0.01
    # (15,5)
    b1 = np.zeros((1,n_h))
    # (1,5)

    W2 = np.random.randn(n_h,n_y) * 0.01
    # (5,1)
    b2 = np.zeros((1,n_y))
    # (1,1)
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [134]:
def cost_function(y,A2):
    cost =  -np.mean(y*np.log(A2) + (1-y)*np.log(1-A2))
    return cost

In [135]:
def forward_propagation(X, parameters) :

    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]

    Z1 = np.dot(X,W1) + b1
    # 220,5
    A1 = sigmoid(Z1).reshape(X.shape[0],b1.shape[1])
    
    Z2 = np.dot(A1,W2) + b2
    # 220,1
    A2 = sigmoid(Z2).reshape(X.shape[0],b2.shape[1])
    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    return cache

In [136]:
def backward_propagation(cache,parameters,X,y,m):
    
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]

    A1 = cache["A1"]
    A2 = cache["A2"]
    Z1 = cache["Z1"]
    Z2 = cache["Z2"]

    dZ2 = A2 - y
    dW2 = (1/m)*(np.dot(A1.T,dZ2))
    db2 = np.mean(dZ2)

    dZ1 = np.dot(dZ2,W2.T)*np.multiply(A1,(A1-1))
    dW1 = (np.dot(X.T,dZ1))
    db1 = (1/m) *(np.sum(dZ1, axis=0, keepdims=True))

    grads = {
        "dW1" : dW1,
        "db1" : db1,
        "dW2" : dW2,
        "db2" : db2
    }

    return grads

In [137]:
def update_parameters(parameters, grads, learning_rate):

    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]

    dW1 = grads["dW1"]
    db1 = grads["db1"]
    dW2 = grads["dW2"]
    db2 = grads["db2"]

    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [144]:
   
n_x = 15
n_y = 1
n_h = 10
iterations = 10000
learning_rate = 0.01
m = X_train.shape[0]

parameters = initialize_parameters(n_x,n_h,n_y)
for i in range(0, iterations) :
    cache = forward_propagation(X_train,parameters)

    grads = backward_propagation(cache,parameters,X_train,y_train,m)

    parameters = update_parameters(parameters, grads, learning_rate)
    if i%500 == 0:
        print("Grads shapes:\n dW1, db1, dW2, db2",grads["dW1"].shape, grads["db1"].shape, grads["dW2"].shape, grads["db2"].shape)
        print("Cost for",i,"iterations",cost_function(y_train, cache["A2"]))
        print(cache["A2"][:5])

Grads shapes:
 dW1, db1, dW2, db2 (15, 10) (1, 10) (10, 1) ()
Cost for 0 iterations 0.6951152105576835
[[0.49862652]
 [0.4986976 ]
 [0.49858027]
 [0.49858264]
 [0.49863714]]
Grads shapes:
 dW1, db1, dW2, db2 (15, 10) (1, 10) (10, 1) ()
Cost for 500 iterations 0.4642301058106518
[[0.74203497]
 [0.74738947]
 [0.73455851]
 [0.73426978]
 [0.73276451]]
Grads shapes:
 dW1, db1, dW2, db2 (15, 10) (1, 10) (10, 1) ()
Cost for 1000 iterations 0.4211010313880673
[[0.79734072]
 [0.79637768]
 [0.80108924]
 [0.80122275]
 [0.80170147]]
Grads shapes:
 dW1, db1, dW2, db2 (15, 10) (1, 10) (10, 1) ()
Cost for 1500 iterations 0.4083113772167229
[[0.82905545]
 [0.8246021 ]
 [0.83082306]
 [0.83085852]
 [0.83153712]]
Grads shapes:
 dW1, db1, dW2, db2 (15, 10) (1, 10) (10, 1) ()
Cost for 2000 iterations 0.4100583619693482
[[0.84413168]
 [0.84225751]
 [0.84428296]
 [0.84424944]
 [0.8444776 ]]
Grads shapes:
 dW1, db1, dW2, db2 (15, 10) (1, 10) (10, 1) ()
Cost for 2500 iterations 0.4115628362125696
[[0.8500537 ]

In [146]:
result = forward_propagation(X_test,parameters)
final = result["A2"]
final[final > 0.5] = 1
final[final < 0.5] = 0

print(np.mean(final == y_test))
print(final,y_test)

0.8928571428571429
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
